deploy:
  provider: releases
  name: v$(grep '^## ' CHANGELOG.md | cut -d "[" -f 2 | cut -d "]" -f 1)
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false

branches:
  only:
    - master
